name: regression second End-to-end tests

on: 
  push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run specific Cypress tests using npx and specifying the exact paths
      - name: Cypress run
        run: |
          npx cypress run \
          --spec "cypress/e2e/TestCheckOut.cy.js" \
          --spec "cypress/e2e/testLogin.cy.js"


